// === Firewall Generator Logic by @DmiBot ===

document.getElementById("generateBtn").addEventListener("click", () => {
    const mode = window.currentMode || 'basic';
    let script = `# === MIKROTIK FIREWALL HARDENING ===\n# Generated by DmiBot Tools\n\n/ip firewall filter\n`;

    // --- COMMON RULES (Standard Hardening) ---
    script += `# 1. Basic Safety Rules\n`;
    script += `add chain=input connection-state=established,related,untracked action=accept comment="Defconf: Accept Established/Related"\n`;
    script += `add chain=input connection-state=invalid action=drop comment="Defconf: Drop Invalid"\n`;
    script += `add chain=input protocol=icmp action=accept comment="Defconf: Accept ICMP"\n\n`;

    if (mode === 'basic') {
        const whiteList = document.getElementById("whiteListIp").value;
        const winboxPort = document.getElementById("winboxPort").value;
        const blockDns = document.getElementById("blockDnsWan").checked;
        const blockScan = document.getElementById("blockScan").checked;

        // Whitelist
        if (whiteList) {
            script += `/ip firewall address-list\n`;
            whiteList.split(',').forEach(ip => {
                if(ip.trim()) script += `add list=SAFE_ADMIN address=${ip.trim()} comment="Admin IP"\n`;
            });
            script += `/ip firewall filter\n`;
            script += `add chain=input src-address-list=SAFE_ADMIN action=accept comment="Accept Admin"\n`;
        }

        // Port Scanner Protection
        if (blockScan) {
            script += `# Block Port Scanners\n`;
            script += `add chain=input protocol=tcp psd=21,3s,3:1 action=add-src-to-address-list address-list="port_scanners" address-list-timeout=2w comment="Detect Port Scanners"\n`;
            script += `add chain=input protocol=tcp tcp-flags=fin,!syn,!rst,!psh,!ack,!urg action=add-src-to-address-list address-list="port_scanners" address-list-timeout=2w comment="Detect NMAP FIN Scan"\n`;
            script += `add chain=input src-address-list="port_scanners" action=drop comment="Drop Port Scanners"\n`;
        }

        // DNS WAN Block
        if (blockDns) {
            script += `add chain=input protocol=udp dst-port=53 in-interface-list=!LAN action=drop comment="Block DNS Request from WAN"\n`;
            script += `add chain=input protocol=tcp dst-port=53 in-interface-list=!LAN action=drop comment="Block DNS Request from WAN"\n`;
        }

        // Winbox
        script += `# Winbox Access\n`;
        script += `add chain=input protocol=tcp dst-port=${winboxPort} action=accept comment="Allow Winbox"\n`;
        
        // Drop Everything Else
        script += `add chain=input in-interface-list=!LAN action=drop comment="Drop All Other Input from WAN"\n`;

    } else if (mode === 'knocking') {
        const k1 = document.getElementById("k1").value;
        const k2 = document.getElementById("k2").value;
        const k3 = document.getElementById("k3").value;
        const openTime = document.getElementById("openTime").value;

        script += `# === PORT KNOCKING LOGIC ===\n`;
        script += `# Sequence: ${k1} -> ${k2} -> ${k3} -> Open Winbox\n\n`;

        // Stage 1
        script += `add chain=input protocol=tcp dst-port=${k1} action=add-src-to-address-list address-list="knocker_stage_1" address-list-timeout=1m comment="Knock 1: Start"\n`;
        
        // Stage 2 (Must have Stage 1)
        script += `add chain=input protocol=tcp dst-port=${k2} src-address-list="knocker_stage_1" action=add-src-to-address-list address-list="knocker_stage_2" address-list-timeout=1m comment="Knock 2"\n`;

        // Stage 3 (Must have Stage 2) -> SUCCESS
        script += `add chain=input protocol=tcp dst-port=${k3} src-address-list="knocker_stage_2" action=add-src-to-address-list address-list="SAFE_WINBOX_USER" address-list-timeout=${openTime}m comment="Knock 3: Success! Access Granted"\n`;

        // Allow Winbox ONLY for SAFE_WINBOX_USER
        script += `\n# Allow Access for Knocker\n`;
        script += `add chain=input protocol=tcp dst-port=8291 src-address-list="SAFE_WINBOX_USER" action=accept comment="Allow Winbox for Knocker"\n`;
        
        // Drop other Winbox attempts
        script += `add chain=input protocol=tcp dst-port=8291 action=drop comment="Drop Illegal Winbox Access"\n`;
    }

    document.getElementById("outputScript").value = script;
});

document.getElementById("copyBtn").addEventListener("click", () => {
    const t = document.getElementById("outputScript");
    t.select(); navigator.clipboard.writeText(t.value).then(() => alert("✅ Script Copied!"));
});
