// === Telegram Monitor Logic by @DmiBot ===

// Helper: Tambah Target
document.getElementById("addTargetBtn").addEventListener("click", () => {
    const container = document.getElementById("targetContainer");
    const div = document.createElement("div");
    div.className = "target-block";
    div.style.cssText = "border:1px solid #ddd; padding:15px; margin-bottom:10px; border-radius:8px; background:#f9f9f9; margin-top:10px;";
    div.innerHTML = `
        <label style="font-size:0.9rem">Nama Monitor (ISP):</label>
        <input class="monName" placeholder="ISP-Cadangan">
        <label style="font-size:0.9rem">IP Target (Ping):</label>
        <input class="monIp" placeholder="1.1.1.1">
        <label style="font-size:0.9rem">Interval Cek:</label>
        <input class="monInterval" value="00:01:00">
        <button type="button" onclick="this.parentElement.remove()" style="background:#f44336; margin-top:10px; padding:5px 10px; font-size:0.8rem;">Hapus</button>
    `;
    container.appendChild(div);
});

document.getElementById("generateBtn").addEventListener("click", () => {
    const token = document.getElementById("botToken").value.trim();
    const chatId = document.getElementById("chatId").value.trim();

    if (!token || !chatId) {
        alert("⚠️ Wajib isi Bot Token dan Chat ID!");
        return;
    }

    let script = `# === TELEGRAM NETWATCH MONITOR ===\n# Generated by DmiBot Tools\n\n`;
    
    // Validasi URL Mikrotik (Menghindari error sertifikat di versi lama)
    script += `/tool fetch url="https://api.telegram.org/" mode=https keep-result=no dst-path=test_connection_dummy\n:delay 2s;\n\n`;

    document.querySelectorAll(".target-block").forEach(block => {
        const name = block.querySelector(".monName").value.trim();
        const ip = block.querySelector(".monIp").value.trim();
        const interval = block.querySelector(".monInterval").value.trim();

        if (name && ip) {
            // Encode Pesan (Ganti spasi dengan %20, emoji manual encoding jika perlu)
            // RouterOS tidak support full URL encode natif, kita main simple replace
            const msgUp = `✅ ${name} IS UP! (Ping ${ip} OK)`;
            const msgDown = `🔴 ${name} IS DOWN! (Ping ${ip} RTO)`;
            
            // Script Fetch Telegram (One-Liner untuk Netwatch)
            // Note: RouterOS string concats bisa tricky. Kita pakai format variable.
            
            script += `# Monitor: ${name} (${ip})\n`;
            script += `/tool netwatch add host="${ip}" interval=${interval} comment="${name} Monitor" disabled=no \\\n`;
            
            // UP SCRIPT
            script += `    up-script={ /tool fetch url="https://api.telegram.org/bot${token}/sendMessage?chat_id=${chatId}&text=${msgUp.replace(/\s/g, "%20")}" mode=https keep-result=no } \\\n`;
            
            // DOWN SCRIPT
            script += `    down-script={ /tool fetch url="https://api.telegram.org/bot${token}/sendMessage?chat_id=${chatId}&text=${msgDown.replace(/\s/g, "%20")}" mode=https keep-result=no }\n\n`;
        }
    });

    document.getElementById("outputScript").value = script;
});

document.getElementById("copyBtn").addEventListener("click", () => {
    const t = document.getElementById("outputScript");
    t.select(); navigator.clipboard.writeText(t.value).then(() => alert("✅ Copied!"));
});
