// === WireGuard Generator Logic by @DmiBot ===

document.getElementById("generateBtn").addEventListener("click", () => {
    // Input Data
    const wgName = document.getElementById("wgName").value;
    const wgPort = document.getElementById("wgPort").value;
    const wgIp = document.getElementById("wgIp").value;
    const publicIp = document.getElementById("publicIp").value || "IP-PUBLIC-ROUTER-ANDA";
    
    const peerName = document.getElementById("peerName").value;
    const peerIp = document.getElementById("peerIp").value;

    // --- 1. SCRIPT MIKROTIK (ROUTER) ---
    let routerScript = `# === WIREGUARD SERVER SETUP ===\n# Generated by DmiBot Tools\n\n`;
    
    routerScript += `# 1. Buat Interface WireGuard\n`;
    routerScript += `/interface wireguard add name=${wgName} listen-port=${wgPort} comment="VPN Server"\n`;
    
    routerScript += `# 2. Pasang IP Address (Gateway)\n`;
    routerScript += `/ip address add address=${wgIp} interface=${wgName} network=${wgIp.split('/')[0].split('.').slice(0,3).join('.')}.0\n`;
    
    routerScript += `# 3. Buka Firewall (Input UDP)\n`;
    routerScript += `/ip firewall filter add chain=input protocol=udp dst-port=${wgPort} action=accept comment="Allow WireGuard"\n`;
    
    routerScript += `\n# --- PEER SETUP (CLIENT) ---\n`;
    routerScript += `# PENTING: Anda harus memasukkan 'Public Key' dari Client di bawah ini.\n`;
    routerScript += `/interface wireguard peers\n`;
    routerScript += `add interface=${wgName} public-key="PASTE_CLIENT_PUBLIC_KEY_HERE" allowed-address=${peerIp} comment="${peerName}"\n`;
    
    routerScript += `\n# --- CARA CEK PUBLIC KEY ROUTER ---\n`;
    routerScript += `# Jalankan perintah ini untuk melihat Public Key Router (Dibutuhkan di HP):\n`;
    routerScript += `/interface wireguard print\n`;

    // --- 2. CONFIG CLIENT (HP/LAPTOP) ---
    let clientConfig = `[Interface]\n`;
    clientConfig += `# Config ini untuk: ${peerName}\n`;
    clientConfig += `PrivateKey = <GENERATE_DI_APLIKASI_HP_LALU_PASTE_SINI>\n`;
    clientConfig += `Address = ${peerIp.replace('/32', '/24')}\n`;
    clientConfig += `DNS = 8.8.8.8\n\n`;
    
    clientConfig += `[Peer]\n`;
    clientConfig += `# Ini adalah data Router Mikrotik Anda\n`;
    clientConfig += `PublicKey = <PASTE_ROUTER_PUBLIC_KEY_HERE>\n`;
    clientConfig += `AllowedIPs = 0.0.0.0/0\n`;
    clientConfig += `Endpoint = ${publicIp}:${wgPort}\n`;
    clientConfig += `PersistentKeepalive = 25\n`;

    // Output
    document.getElementById("outputRouter").value = routerScript;
    document.getElementById("outputClient").value = clientConfig;
});
