#!/bin/bash

echo "🛡️ Menginstal Fitur: Firewall Hardening & Port Knocking..."

# 1. BUAT FILE HTML
cat << 'EOF' > firewall_security_tool.html
<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Firewall Hardening | DmiBot</title>
<link rel="icon" href="Mikrotik.svg">
<link rel="stylesheet" href="style.css">
</head>
<body>

<header>
  <button class="home-btn" onclick="window.location.href='index.html'">🏠 Home</button>
  <h1>🛡️ Firewall Hardening</h1>
  <p>Amankan Router dari Serangan Brute Force & Scanner</p>
</header>

<main>
  <div class="tabs">
    <button id="tab1" class="active" onclick="openMode('basic')">🧱 Basic Protection</button>
    <button id="tab2" onclick="openMode('knocking')">🚪 Port Knocking (Advanced)</button>
  </div>

  <div id="basicMode" class="mode-content">
    <div class="card">
        <h3>🔒 Input Chain Protection</h3>
        <p>Konfigurasi standar untuk mengamankan router dari akses luar yang tidak diinginkan.</p>
        
        <label>Whitelist IP (Admin/VPN/Kantor):</label>
        <input id="whiteListIp" placeholder="192.168.1.0/24, 10.10.10.2">
        
        <label>Port Winbox (Default 8291):</label>
        <input id="winboxPort" value="8291" placeholder="8291">
        
        <label style="display:flex; align-items:center; margin-top:10px;">
            <input type="checkbox" id="blockDnsWan" checked style="width:auto; margin-right:10px;">
            Block DNS Request dari WAN (Cegah DDoS Amplification)
        </label>
        
        <label style="display:flex; align-items:center;">
            <input type="checkbox" id="blockScan" checked style="width:auto; margin-right:10px;">
            Block Port Scanners (PSD)
        </label>
    </div>
  </div>

  <div id="knockingMode" class="mode-content hidden">
    <div class="card" style="border: 1px solid #2196F3;">
        <h3 style="color:#1976D2;">🚪 Port Knocking Generator</h3>
        <p>Sembunyikan port Winbox! Port hanya akan terbuka jika Anda melakukan "ketukan" ke urutan port berikut.</p>
        
        <div style="display:grid; grid-template-columns: 1fr 1fr 1fr; gap:10px;">
            <div>
                <label>Knock 1 (TCP):</label>
                <input id="k1" value="1234" placeholder="1234">
            </div>
            <div>
                <label>Knock 2 (TCP):</label>
                <input id="k2" value="5678" placeholder="5678">
            </div>
            <div>
                <label>Knock 3 (TCP):</label>
                <input id="k3" value="9000" placeholder="9000">
            </div>
        </div>
        <p style="font-size:0.8rem; color:#666;">*Ingat urutan port ini. Akses IP router pada port tersebut berurutan untuk membuka akses.</p>
        
        <label>Durasi Akses Terbuka (Menit):</label>
        <input id="openTime" value="60" placeholder="60">
    </div>
  </div>

  <button id="generateBtn" style="width:100%; font-size:1.2rem; background:#FF5722;">🛡️ Generate Firewall Script</button>

  <div class="card">
    <h3>📜 Output Script</h3>
    <textarea id="outputScript" readonly onclick="this.select()" style="height:350px;" placeholder="Klik Generate..."></textarea>
    <button id="copyBtn">📋 Copy Script</button>
  </div>
</main>

<footer><p style="text-align:center; padding:20px; color:#777;">&copy; 2025 DmiBot Projects</p></footer>

<script src="modules/firewall_tool.js"></script>
<script>
    function openMode(mode) {
        document.querySelectorAll('.tabs button').forEach(b => b.classList.remove('active'));
        document.getElementById(mode === 'basic' ? 'tab1' : 'tab2').classList.add('active');
        
        document.getElementById('basicMode').classList.toggle('hidden', mode !== 'basic');
        document.getElementById('knockingMode').classList.toggle('hidden', mode !== 'knocking');
        
        // Set global mode for JS module
        window.currentMode = mode;
    }
    window.currentMode = 'basic'; // default
</script>
</body>
</html>
EOF

# 2. BUAT FILE JS MODULE
cat << 'EOF' > modules/firewall_tool.js
// === Firewall Generator Logic by @DmiBot ===

document.getElementById("generateBtn").addEventListener("click", () => {
    const mode = window.currentMode || 'basic';
    let script = `# === MIKROTIK FIREWALL HARDENING ===\n# Generated by DmiBot Tools\n\n/ip firewall filter\n`;

    // --- COMMON RULES (Standard Hardening) ---
    script += `# 1. Basic Safety Rules\n`;
    script += `add chain=input connection-state=established,related,untracked action=accept comment="Defconf: Accept Established/Related"\n`;
    script += `add chain=input connection-state=invalid action=drop comment="Defconf: Drop Invalid"\n`;
    script += `add chain=input protocol=icmp action=accept comment="Defconf: Accept ICMP"\n\n`;

    if (mode === 'basic') {
        const whiteList = document.getElementById("whiteListIp").value;
        const winboxPort = document.getElementById("winboxPort").value;
        const blockDns = document.getElementById("blockDnsWan").checked;
        const blockScan = document.getElementById("blockScan").checked;

        // Whitelist
        if (whiteList) {
            script += `/ip firewall address-list\n`;
            whiteList.split(',').forEach(ip => {
                if(ip.trim()) script += `add list=SAFE_ADMIN address=${ip.trim()} comment="Admin IP"\n`;
            });
            script += `/ip firewall filter\n`;
            script += `add chain=input src-address-list=SAFE_ADMIN action=accept comment="Accept Admin"\n`;
        }

        // Port Scanner Protection
        if (blockScan) {
            script += `# Block Port Scanners\n`;
            script += `add chain=input protocol=tcp psd=21,3s,3:1 action=add-src-to-address-list address-list="port_scanners" address-list-timeout=2w comment="Detect Port Scanners"\n`;
            script += `add chain=input protocol=tcp tcp-flags=fin,!syn,!rst,!psh,!ack,!urg action=add-src-to-address-list address-list="port_scanners" address-list-timeout=2w comment="Detect NMAP FIN Scan"\n`;
            script += `add chain=input src-address-list="port_scanners" action=drop comment="Drop Port Scanners"\n`;
        }

        // DNS WAN Block
        if (blockDns) {
            script += `add chain=input protocol=udp dst-port=53 in-interface-list=!LAN action=drop comment="Block DNS Request from WAN"\n`;
            script += `add chain=input protocol=tcp dst-port=53 in-interface-list=!LAN action=drop comment="Block DNS Request from WAN"\n`;
        }

        // Winbox
        script += `# Winbox Access\n`;
        script += `add chain=input protocol=tcp dst-port=${winboxPort} action=accept comment="Allow Winbox"\n`;
        
        // Drop Everything Else
        script += `add chain=input in-interface-list=!LAN action=drop comment="Drop All Other Input from WAN"\n`;

    } else if (mode === 'knocking') {
        const k1 = document.getElementById("k1").value;
        const k2 = document.getElementById("k2").value;
        const k3 = document.getElementById("k3").value;
        const openTime = document.getElementById("openTime").value;

        script += `# === PORT KNOCKING LOGIC ===\n`;
        script += `# Sequence: ${k1} -> ${k2} -> ${k3} -> Open Winbox\n\n`;

        // Stage 1
        script += `add chain=input protocol=tcp dst-port=${k1} action=add-src-to-address-list address-list="knocker_stage_1" address-list-timeout=1m comment="Knock 1: Start"\n`;
        
        // Stage 2 (Must have Stage 1)
        script += `add chain=input protocol=tcp dst-port=${k2} src-address-list="knocker_stage_1" action=add-src-to-address-list address-list="knocker_stage_2" address-list-timeout=1m comment="Knock 2"\n`;

        // Stage 3 (Must have Stage 2) -> SUCCESS
        script += `add chain=input protocol=tcp dst-port=${k3} src-address-list="knocker_stage_2" action=add-src-to-address-list address-list="SAFE_WINBOX_USER" address-list-timeout=${openTime}m comment="Knock 3: Success! Access Granted"\n`;

        // Allow Winbox ONLY for SAFE_WINBOX_USER
        script += `\n# Allow Access for Knocker\n`;
        script += `add chain=input protocol=tcp dst-port=8291 src-address-list="SAFE_WINBOX_USER" action=accept comment="Allow Winbox for Knocker"\n`;
        
        // Drop other Winbox attempts
        script += `add chain=input protocol=tcp dst-port=8291 action=drop comment="Drop Illegal Winbox Access"\n`;
    }

    document.getElementById("outputScript").value = script;
});

document.getElementById("copyBtn").addEventListener("click", () => {
    const t = document.getElementById("outputScript");
    t.select(); navigator.clipboard.writeText(t.value).then(() => alert("✅ Script Copied!"));
});
EOF

# 3. UPDATE INDEX.HTML (TAMBAH MENU)
cat << 'EOF' > index.html
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mikrotik Tools Portal | DmiBot</title>
    <meta name="description" content="Kumpulan Tools Generator Script Mikrotik Otomatis.">
    <link rel="icon" href="Mikrotik.svg">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>🛠️ DmiBot Mikrotik Tools</h1>
        <p>Generator Konfigurasi Jaringan Otomatis</p>
    </header>
    <main>
        <div class="menu-grid">
            <div class="menu-card" onclick="window.location.href='mikrotik_load_balance_tools.html'">
                <div class="icon">⚙️</div>
                <h3>Load Balance & PCC</h3>
                <p>Setup Dual WAN, Failover, dan Basic Network dalam sekali klik.</p>
            </div>
            
            <div class="menu-card" onclick="window.location.href='pbr_game_calculator.html'">
                <div class="icon">🎮</div>
                <h3>PBR Game Calculator</h3>
                <p>Pisahkan trafik Game ke ISP khusus dengan port terupdate.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='pbr_sosmed_tool.html'">
                <div class="icon">📱</div>
                <h3>Sosmed Routing</h3>
                <p>Routing khusus trafik Sosial Media (TikTok, FB, IG) via RAW/Mangle.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='telegram_monitor_tool.html'">
                <div class="icon">📢</div>
                <h3>Netwatch Telegram</h3>
                <p>Notifikasi otomatis ke HP saat internet/ISP mati.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='firewall_security_tool.html'">
                <div class="icon">🛡️</div>
                <h3>Firewall Hardening</h3>
                <p>Amankan Router dari serangan dan fitur Port Knocking.</p>
            </div>
        </div>
    </main>
    <footer>
        <p style="text-align:center; padding:20px; color:#777;">&copy; 2025 DmiBot Projects</p>
    </footer>
</body>
</html>
EOF

echo "✅ Fitur Firewall & Port Knocking Berhasil Diinstal!"