#!/bin/bash

echo "🚀 Menginstal Fitur: Netwatch & Telegram Notification..."

# 1. BUAT FILE HTML: telegram_monitor_tool.html
cat << 'EOF' > telegram_monitor_tool.html
<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Telegram Monitor Tool | DmiBot</title>
<link rel="icon" href="Mikrotik.svg">
<link rel="stylesheet" href="style.css">
</head>
<body>

<header>
  <button class="home-btn" onclick="window.location.href='index.html'">🏠 Home</button>
  <h1>📢 Netwatch Telegram</h1>
  <p>Monitoring Status Internet Real-time</p>
</header>

<main>
  <div class="card">
    <h3>🤖 Konfigurasi Bot Telegram</h3>
    <div style="background:#e3f2fd; border:1px solid #90caf9; padding:10px; border-radius:5px; margin-bottom:15px;">
        <p style="margin:0; font-size:0.85rem;">ℹ️ <strong>Info:</strong> Buat bot di @BotFather untuk dapat Token, dan chat ke @userinfobot untuk dapat ID Anda.</p>
    </div>
    
    <label>Bot Token:</label>
    <input id="botToken" type="text" placeholder="123456789:ABCdefGHIjklMNOpqrs...">
    
    <label>Chat ID (User/Group):</label>
    <input id="chatId" type="text" placeholder="12345678">
  </div>

  <div class="card">
    <h3>🎯 Target Monitoring</h3>
    <p>Masukkan IP yang ingin dipantau (misal: Gateway ISP atau Google DNS).</p>
    
    <div id="targetContainer">
        <div class="target-block" style="border:1px solid #ddd; padding:15px; margin-bottom:10px; border-radius:8px; background:#f9f9f9;">
            <label style="font-size:0.9rem">Nama Monitor (ISP):</label>
            <input class="monName" value="ISP-INDIHOME" placeholder="ISP-Utama">
            
            <label style="font-size:0.9rem">IP Target (Ping):</label>
            <input class="monIp" value="8.8.8.8" placeholder="8.8.8.8">
            
            <label style="font-size:0.9rem">Interval Cek:</label>
            <input class="monInterval" value="00:01:00" placeholder="00:01:00">
        </div>
    </div>
    
    <button id="addTargetBtn" type="button" style="background:#2196F3;">+ Tambah Target Lain</button>
  </div>

  <button id="generateBtn" style="width:100%; font-size:1.2rem;">🚀 Generate Script</button>

  <div class="card">
    <h3>📜 Output Script</h3>
    <textarea id="outputScript" readonly onclick="this.select()" placeholder="Klik Generate..." style="height:300px;"></textarea>
    <button id="copyBtn">📋 Copy Script</button>
  </div>
</main>

<footer><p style="text-align:center; padding:20px; color:#777;">&copy; 2025 DmiBot Projects</p></footer>

<script src="modules/telegram_monitor.js"></script>
</body>
</html>
EOF

# 2. BUAT FILE JS MODULE: modules/telegram_monitor.js
cat << 'EOF' > modules/telegram_monitor.js
// === Telegram Monitor Logic by @DmiBot ===

// Helper: Tambah Target
document.getElementById("addTargetBtn").addEventListener("click", () => {
    const container = document.getElementById("targetContainer");
    const div = document.createElement("div");
    div.className = "target-block";
    div.style.cssText = "border:1px solid #ddd; padding:15px; margin-bottom:10px; border-radius:8px; background:#f9f9f9; margin-top:10px;";
    div.innerHTML = `
        <label style="font-size:0.9rem">Nama Monitor (ISP):</label>
        <input class="monName" placeholder="ISP-Cadangan">
        <label style="font-size:0.9rem">IP Target (Ping):</label>
        <input class="monIp" placeholder="1.1.1.1">
        <label style="font-size:0.9rem">Interval Cek:</label>
        <input class="monInterval" value="00:01:00">
        <button type="button" onclick="this.parentElement.remove()" style="background:#f44336; margin-top:10px; padding:5px 10px; font-size:0.8rem;">Hapus</button>
    `;
    container.appendChild(div);
});

document.getElementById("generateBtn").addEventListener("click", () => {
    const token = document.getElementById("botToken").value.trim();
    const chatId = document.getElementById("chatId").value.trim();

    if (!token || !chatId) {
        alert("⚠️ Wajib isi Bot Token dan Chat ID!");
        return;
    }

    let script = `# === TELEGRAM NETWATCH MONITOR ===\n# Generated by DmiBot Tools\n\n`;
    
    // Validasi URL Mikrotik (Menghindari error sertifikat di versi lama)
    script += `/tool fetch url="https://api.telegram.org/" mode=https keep-result=no dst-path=test_connection_dummy\n:delay 2s;\n\n`;

    document.querySelectorAll(".target-block").forEach(block => {
        const name = block.querySelector(".monName").value.trim();
        const ip = block.querySelector(".monIp").value.trim();
        const interval = block.querySelector(".monInterval").value.trim();

        if (name && ip) {
            // Encode Pesan (Ganti spasi dengan %20, emoji manual encoding jika perlu)
            // RouterOS tidak support full URL encode natif, kita main simple replace
            const msgUp = `✅ ${name} IS UP! (Ping ${ip} OK)`;
            const msgDown = `🔴 ${name} IS DOWN! (Ping ${ip} RTO)`;
            
            // Script Fetch Telegram (One-Liner untuk Netwatch)
            // Note: RouterOS string concats bisa tricky. Kita pakai format variable.
            
            script += `# Monitor: ${name} (${ip})\n`;
            script += `/tool netwatch add host="${ip}" interval=${interval} comment="${name} Monitor" disabled=no \\\n`;
            
            // UP SCRIPT
            script += `    up-script={ /tool fetch url="https://api.telegram.org/bot${token}/sendMessage?chat_id=${chatId}&text=${msgUp.replace(/\s/g, "%20")}" mode=https keep-result=no } \\\n`;
            
            // DOWN SCRIPT
            script += `    down-script={ /tool fetch url="https://api.telegram.org/bot${token}/sendMessage?chat_id=${chatId}&text=${msgDown.replace(/\s/g, "%20")}" mode=https keep-result=no }\n\n`;
        }
    });

    document.getElementById("outputScript").value = script;
});

document.getElementById("copyBtn").addEventListener("click", () => {
    const t = document.getElementById("outputScript");
    t.select(); navigator.clipboard.writeText(t.value).then(() => alert("✅ Copied!"));
});
EOF

# 3. UPDATE INDEX.HTML (TAMBAH MENU BARU)
# Kita rewrite index.html agar menu Telegram masuk
cat << 'EOF' > index.html
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mikrotik Tools Portal | DmiBot</title>
    <meta name="description" content="Kumpulan Tools Generator Script Mikrotik Otomatis.">
    <link rel="icon" href="Mikrotik.svg">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>🛠️ DmiBot Mikrotik Tools</h1>
        <p>Generator Konfigurasi Jaringan Otomatis</p>
    </header>
    <main>
        <div class="menu-grid">
            <div class="menu-card" onclick="window.location.href='mikrotik_load_balance_tools.html'">
                <div class="icon">⚙️</div>
                <h3>Load Balance & PCC</h3>
                <p>Setup Dual WAN, Failover, dan Basic Network dalam sekali klik.</p>
            </div>
            
            <div class="menu-card" onclick="window.location.href='pbr_game_calculator.html'">
                <div class="icon">🎮</div>
                <h3>PBR Game Calculator</h3>
                <p>Pisahkan trafik Game ke ISP khusus dengan port terupdate.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='pbr_sosmed_tool.html'">
                <div class="icon">📱</div>
                <h3>Sosmed Routing</h3>
                <p>Routing khusus trafik Sosial Media (TikTok, FB, IG) via RAW/Mangle.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='telegram_monitor_tool.html'">
                <div class="icon">📢</div>
                <h3>Netwatch Telegram</h3>
                <p>Notifikasi otomatis ke HP saat internet/ISP mati.</p>
            </div>
        </div>
    </main>
    <footer>
        <p style="text-align:center; padding:20px; color:#777;">&copy; 2025 DmiBot Projects</p>
    </footer>
</body>
</html>
EOF

echo "✅ Fitur Telegram Notification Berhasil Diinstal!"