#!/bin/bash

echo "🔐 Menginstal Fitur: WireGuard VPN Generator..."

# 1. BUAT FILE HTML
cat << 'EOF' > vpn_wireguard_tool.html
<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WireGuard VPN Tool | DmiBot</title>
<link rel="icon" href="Mikrotik.svg">
<link rel="stylesheet" href="style.css">
</head>
<body>

<header>
  <button class="home-btn" onclick="window.location.href='index.html'">🏠 Home</button>
  <h1>🔐 WireGuard VPN Generator</h1>
  <p>Setup VPN Paling Cepat & Ringan untuk RouterOS v7</p>
</header>

<main>
  <div class="card">
    <h3>📡 Konfigurasi Server (Mikrotik)</h3>
    <div style="display:grid; grid-template-columns: 1fr 1fr; gap:15px;">
        <div>
            <label>Nama Interface:</label>
            <input id="wgName" value="wireguard1" placeholder="wireguard1">
        </div>
        <div>
            <label>Listen Port (UDP):</label>
            <input id="wgPort" value="13231" placeholder="13231">
        </div>
    </div>
    
    <label>IP Address VPN (Gateway):</label>
    <input id="wgIp" value="10.10.100.1/24" placeholder="10.10.100.1/24">
    
    <label>IP Public / DDNS Router (Penting untuk Client):</label>
    <input id="publicIp" placeholder="202.134.x.x atau id-router.sn.mynetname.net">
  </div>

  <div class="card">
    <h3>📱 Konfigurasi Client (HP/Laptop)</h3>
    <label>Nama Client (Peer):</label>
    <input id="peerName" value="HP-Admin" placeholder="HP-Admin">
    
    <label>IP Address Client:</label>
    <input id="peerIp" value="10.10.100.2/32" placeholder="10.10.100.2/32">
    
    <div style="background:#fff3e0; border:1px solid #ffe0b2; padding:10px; margin-top:10px; border-radius:5px;">
        <p style="margin:0; font-size:0.85rem; color:#E65100;">
            ⚠️ <strong>Info Key:</strong> Karena keterbatasan browser, Key harus digenerate di perangkat masing-masing. Script ini menyediakan <strong>Placeholder</strong>.
        </p>
    </div>
  </div>

  <button id="generateBtn" style="width:100%; font-size:1.2rem; background:#673AB7;">🔐 Generate Config</button>

  <div class="tabs" style="margin-top:20px;">
    <button id="tab1" class="active" onclick="openOut('router')">📜 Script RouterOS</button>
    <button id="tab2" onclick="openOut('client')">📱 Config Client (.conf)</button>
  </div>

  <div id="outRouter" class="out-content">
    <div class="card">
        <p>Copy script ini ke Terminal Mikrotik:</p>
        <textarea id="outputRouter" readonly onclick="this.select()" style="height:300px;"></textarea>
    </div>
  </div>

  <div id="outClient" class="out-content hidden">
    <div class="card">
        <p>Copy text ini, simpan sebagai file <code>wg-client.conf</code> lalu import ke HP:</p>
        <textarea id="outputClient" readonly onclick="this.select()" style="height:300px;"></textarea>
    </div>
  </div>

</main>

<footer><p style="text-align:center; padding:20px; color:#777;">&copy; 2025 DmiBot Projects</p></footer>

<script src="modules/wireguard_tool.js"></script>
<script>
    function openOut(mode) {
        document.querySelectorAll('.tabs button').forEach(b => b.classList.remove('active'));
        document.getElementById(mode === 'router' ? 'tab1' : 'tab2').classList.add('active');
        document.getElementById('outRouter').classList.toggle('hidden', mode !== 'router');
        document.getElementById('outClient').classList.toggle('hidden', mode !== 'client');
    }
</script>
</body>
</html>
EOF

# 2. BUAT FILE JS MODULE
cat << 'EOF' > modules/wireguard_tool.js
// === WireGuard Generator Logic by @DmiBot ===

document.getElementById("generateBtn").addEventListener("click", () => {
    // Input Data
    const wgName = document.getElementById("wgName").value;
    const wgPort = document.getElementById("wgPort").value;
    const wgIp = document.getElementById("wgIp").value;
    const publicIp = document.getElementById("publicIp").value || "IP-PUBLIC-ROUTER-ANDA";
    
    const peerName = document.getElementById("peerName").value;
    const peerIp = document.getElementById("peerIp").value;

    // --- 1. SCRIPT MIKROTIK (ROUTER) ---
    let routerScript = `# === WIREGUARD SERVER SETUP ===\n# Generated by DmiBot Tools\n\n`;
    
    routerScript += `# 1. Buat Interface WireGuard\n`;
    routerScript += `/interface wireguard add name=${wgName} listen-port=${wgPort} comment="VPN Server"\n`;
    
    routerScript += `# 2. Pasang IP Address (Gateway)\n`;
    routerScript += `/ip address add address=${wgIp} interface=${wgName} network=${wgIp.split('/')[0].split('.').slice(0,3).join('.')}.0\n`;
    
    routerScript += `# 3. Buka Firewall (Input UDP)\n`;
    routerScript += `/ip firewall filter add chain=input protocol=udp dst-port=${wgPort} action=accept comment="Allow WireGuard"\n`;
    
    routerScript += `\n# --- PEER SETUP (CLIENT) ---\n`;
    routerScript += `# PENTING: Anda harus memasukkan 'Public Key' dari Client di bawah ini.\n`;
    routerScript += `/interface wireguard peers\n`;
    routerScript += `add interface=${wgName} public-key="PASTE_CLIENT_PUBLIC_KEY_HERE" allowed-address=${peerIp} comment="${peerName}"\n`;
    
    routerScript += `\n# --- CARA CEK PUBLIC KEY ROUTER ---\n`;
    routerScript += `# Jalankan perintah ini untuk melihat Public Key Router (Dibutuhkan di HP):\n`;
    routerScript += `/interface wireguard print\n`;

    // --- 2. CONFIG CLIENT (HP/LAPTOP) ---
    let clientConfig = `[Interface]\n`;
    clientConfig += `# Config ini untuk: ${peerName}\n`;
    clientConfig += `PrivateKey = <GENERATE_DI_APLIKASI_HP_LALU_PASTE_SINI>\n`;
    clientConfig += `Address = ${peerIp.replace('/32', '/24')}\n`;
    clientConfig += `DNS = 8.8.8.8\n\n`;
    
    clientConfig += `[Peer]\n`;
    clientConfig += `# Ini adalah data Router Mikrotik Anda\n`;
    clientConfig += `PublicKey = <PASTE_ROUTER_PUBLIC_KEY_HERE>\n`;
    clientConfig += `AllowedIPs = 0.0.0.0/0\n`;
    clientConfig += `Endpoint = ${publicIp}:${wgPort}\n`;
    clientConfig += `PersistentKeepalive = 25\n`;

    // Output
    document.getElementById("outputRouter").value = routerScript;
    document.getElementById("outputClient").value = clientConfig;
});
EOF

# 3. UPDATE INDEX.HTML
cat << 'EOF' > index.html
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mikrotik Tools Portal | DmiBot</title>
    <meta name="description" content="Kumpulan Tools Generator Script Mikrotik Otomatis.">
    <link rel="icon" href="Mikrotik.svg">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>🛠️ DmiBot Mikrotik Tools</h1>
        <p>Generator Konfigurasi Jaringan Otomatis</p>
    </header>
    <main>
        <div class="menu-grid">
            <div class="menu-card" onclick="window.location.href='mikrotik_load_balance_tools.html'">
                <div class="icon">⚙️</div>
                <h3>Load Balance & PCC</h3>
                <p>Setup Dual WAN, Failover, dan Basic Network dalam sekali klik.</p>
            </div>
            
            <div class="menu-card" onclick="window.location.href='pbr_game_calculator.html'">
                <div class="icon">🎮</div>
                <h3>PBR Game Calculator</h3>
                <p>Pisahkan trafik Game ke ISP khusus dengan port terupdate.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='pbr_sosmed_tool.html'">
                <div class="icon">📱</div>
                <h3>Sosmed Routing</h3>
                <p>Routing khusus trafik Sosial Media (TikTok, FB, IG) via RAW/Mangle.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='telegram_monitor_tool.html'">
                <div class="icon">📢</div>
                <h3>Netwatch Telegram</h3>
                <p>Notifikasi otomatis ke HP saat internet/ISP mati.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='firewall_security_tool.html'">
                <div class="icon">🛡️</div>
                <h3>Firewall Hardening</h3>
                <p>Amankan Router dari serangan dan fitur Port Knocking.</p>
            </div>

            <div class="menu-card" onclick="window.location.href='vpn_wireguard_tool.html'">
                <div class="icon">🔐</div>
                <h3>WireGuard VPN</h3>
                <p>Generator Config Server & Client untuk VPN super cepat.</p>
            </div>
        </div>
    </main>
    <footer>
        <p style="text-align:center; padding:20px; color:#777;">&copy; 2025 DmiBot Projects</p>
    </footer>
</body>
</html>
EOF

echo "✅ Fitur WireGuard VPN Generator Berhasil Diinstal!"